image: docker/compose:1.29.2

stages:
    - build
    - test
    - push
    - deploy

build:
    stage: build
    script: 
        - docker-compose build

test:
    stage: test
    script:
        - docker-compose run frontend npm test -- --watchAll=false

push:
    stage: push
    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script:
        - docker-compose push
