stages:
    - build
    - test
    - deploy

build:
    image: docker/compose
    stage: build
    script: 
        - docker-compose build

test:
    stage: test
    script:
        - docker-compose run frontend npm test -- --watchAll=false
