version: '3'

services:

  db:
    restart: always
    container_name: db
    image: mysql:5.7.43
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "--password=${MYSQL_ROOT_PASSWORD}",
          "--silent"
        ]
      interval: 3s
      retries: 5
      start_period: 30s
    networks:
      - java_mysql

  backend:
    image: $CI_REGISTRY_IMAGE/backend:$BACKEND_IMAGE_TAG
    restart: always
    container_name: backend
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1
      interval: 10s
      timeout: 2s
      retries: 10
    ports:
      - "8080:8080"
    networks:
      - java_js
      - java_mysql

  frontend:
    image: $CI_REGISTRY_IMAGE/frontend:$FRONTEND_IMAGE_TAG
    container_name: frontend
    build: ./frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:3000"
    networks:
      - java_js

networks:
  java_mysql:
    driver: bridge
  java_js:
    driver: bridge

volumes:
  db:
